[package]
name = "bombs-ahoy"
version = "0.1.0"
authors = ["alexdevteam <alexpro820@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", tag = "v0.4.0" }
